name: Build

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "README.md"
    tags:
      - "v*"

jobs:
  desktop-build:
    strategy:
      matrix:
        os: [ macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          pip3 install --upgrade pip setuptools
          pip3 install pyinstaller
          pip3 install -r requirements.txt

      - name: Pyinstaller Build
        run: |
          pyinstaller main.spec --distpath .

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: LiveRecorder_${{ runner.os }}_${{ github.ref_name }}
          path: |
            config.json
            LiveRecorder*

      - name: Create Archive
        if: startsWith(github.ref_name, 'v')
        uses: thedoctor0/zip-release@main
        with:
          filename: LiveRecorder_${{ runner.os }}_${{ github.ref_name }}.zip
          path: |
            config.json
            LiveRecorder*

      - name: Release
        if: startsWith(github.ref_name, 'v')
        uses: softprops/action-gh-release@v1
        with:
          files: ./*.zip

  linux-build:
    strategy:
      matrix:
        arch: [ amd64, arm64 ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Amd64 Build
        if: ${{ matrix.arch == 'amd64' }}
        run: |
          pip3 install --upgrade pip setuptools
          pip3 install pyinstaller staticx
          pip3 install -r requirements.txt
          pyinstaller main.spec
          staticx dist/LiveRecorder LiveRecorder

      - name: Arm64 Build
        if: ${{ matrix.arch == 'arm64' }}
        uses: pguyot/arm-runner-action@v2
        with:
          base_image: raspios_lite_arm64:latest
          copy_artifact_path: LiveRecorder
          commands: |
            sudo apt install python3-pip -y
            pip3 install --upgrade pip setuptools
            pip3 install pyinstaller
            pip3 install -r requirements.txt
            pyinstaller main.spec --distpath .

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: LiveRecorder_${{ runner.os }}_${{ matrix.arch }}_${{ github.ref_name }}
          path: |
            config.json
            LiveRecorder*

      - name: Create Archive
        if: startsWith(github.ref_name, 'v')
        uses: thedoctor0/zip-release@main
        with:
          filename: LiveRecorder_${{ runner.os }}_${{ matrix.arch }}_${{ github.ref_name }}.zip
          path: |
            config.json
            LiveRecorder*

      - name: Release
        if: startsWith(github.ref_name, 'v')
        uses: softprops/action-gh-release@v1
        with:
          files: ./*.zip
